version: '3.8'
services:
  zookeeper1:
    image: bitnami/zookeeper:latest
    container_name: zookeeper1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888
    ports:
      - "2181:2181"
    volumes:
      - zookeeper1_data:/bitnami/zookeeper
    networks:
      - kafka-network

  zookeeper2:
    image: bitnami/zookeeper:latest
    container_name: zookeeper2
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888
    ports:
      - "2182:2181"
    volumes:
      - zookeeper2_data:/bitnami/zookeeper
    networks:
      - kafka-network

  kafka1:
    image: bitnami/kafka:latest
    container_name: kafka1
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2182
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9092,EXTERNAL://DESKTOP-0KK53IH:9094 # CHANGE YOUR EXTERNAL HOST
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=90000
    depends_on:
      - zookeeper1
      - zookeeper2
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - kafka1_data:/bitnami/kafka
    networks:
      - kafka-network

  kafka2:
    image: bitnami/kafka:latest
    container_name: kafka2
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2182
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:9093,EXTERNAL://DESKTOP-0KK53IH:9095 # CHANGE YOUR EXTERNAL HOST
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,EXTERNAL://:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=90000
    depends_on:
      - zookeeper1
      - zookeeper2
    ports:
      - "9093:9093"
      - "9095:9095"
    volumes:
      - kafka2_data:/bitnami/kafka
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9093
    ports:
      - "8080:8080"
    depends_on:
      - kafka1
      - kafka2
    
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
    name: kafka-network

volumes:
  zookeeper1_data:
    name: zookeeper1_data
  zookeeper2_data:
    name: zookeeper2_data
  kafka1_data:
    name: kafka1_data
  kafka2_data:
    name: kafka2_data
